#! /bin/sh
# /etc/init.d

### BEGIN INIT INFO
# Provides: radiopi
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: noip server
# Description:
### END INIT INFO
 
case "$1" in
	start)
        	echo "RadioPi wird gestartet"
        	# Starte Programm
		mocp -S
		alsactl --file  /home/hara/asound.state restore
		mocp --playit /home/hara/radiopi/ready.mp3
        	python /home/hara/radiopi/radio.py
        	;;
	stop)
		echo "RadioPi wird beendet"
        	# Beende Programm
        	mocp -x
		pkill -f /home/hara/radiopi/radio.py
        	;;
	restart)
 		#Aktion wenn restart uebergeben wird
 		echo "RadioPi wird beendet"
        	mocp -x
		pkill -f /home/hara/radiopi/radio.py
		echo "RadioPi wird gestartet"
		mocp -S
		alsactl --file  /home/hara/asound.state restore
		mocp --playit /home/hara/radiopi/ready.mp3
		python /home/hara/radiopi/radio.py
		;;

	*)
		echo "Benutzt: /etc/init.d/radiopi {start|stop|restart}"
		exit 1
        	;;
esac
 
exit 0
