#!/bin/bash
# /root/.moc/editplaylist
mocp -Q%t>/home/hara/.moc/titel
mocp -Q%a>/home/hara/.moc/artist
if mocp -i | grep -q "/home/hara/musik/"; then
    sed -i '1,2d' /home/hara/.moc/playlist.m3u
fi
