#!/bin/bash
# /root/.moc/editplaylist
sudo mocp -Q%t>/root/.moc/titel
sudo mocp -Q%a>/root/.moc/artist
if sudo mocp -i | grep -q "/home/hara/musik/"; then
    sudo sed -i '1,2d' /root/.moc/playlist.m3u
fi
